name: CI - Server tests (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, AE/path-v01, AE/path-v01B]
  workflow_dispatch: {}

jobs:
  server-tests:
    name: Server tests (PR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure CI Environment and Dependencies
        run: ./scripts/verify-ci-env.sh

      - name: Install root deps
        run: npm ci

      - name: Install server deps
        run: npm --prefix server ci

      - name: Run server tests
        run: npm --prefix server test --silent

      - name: Upload server logs (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-tests-logs
          path: server/logs/**
